config/routes.rb
Rails.application.routes.draw do

  get 'games/index'
  get 'games/update', to: 'games#update'
  get 'games/highscore', to: 'games#show'
  get 'games/directions', to: 'games#directions'
  resources :games
  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base

#   set default game values
  def init
    self.p_score = 0
    self.p_loss_counter = 0
    self.level = 1
    player_stats
    self.p_last_move = 'None'
    self.npc_last_move = 'None'
    self.npc_win = FALSE
    self.p_win = FALSE
    self.retry = FALSE
    self.npc_bleed = FALSE
    self.p_bleed = FALSE



    save!
  end

  #Set player stats
  def player_stats
    self.p_max_health = 100 + self.level * 10
    self.p_max_armor = 100 + self.level * 10
    self.p_max_attack = 100 + self.level * 10
    self.p_max_speed = 100 + self.level * 10

    #The additional stat selected by user
    case self.p_stat_boost
      when 'Stamina'
        self.p_max_health += 10
      when 'Defense'
        self.p_max_armor += 10
      when 'Speed'
        self.p_max_speed += 10
      when 'Strength'
        self.p_max_attack += 10
      else
        puts "Not a possible Stat selection"
    end

    self.p_cur_health = self.p_max_health
    self.p_cur_armor = self.p_max_armor
    self.p_cur_attack = self.p_max_attack
    self.p_cur_speed = self.p_max_speed
    save!
  end

  #Used to access NPC Model Data to update the current NPC displayed and stats
  def update_npc(npc_name, npc_file, npc_wild, npc_offense, npc_defense,
               npc_max_health, npc_max_armor, npc_max_attack, npc_max_speed)
    self.npc_max_armor = npc_max_armor + self.level * 10
    self.npc_max_attack = npc_max_attack + self.level * 10
    self.npc_max_health = npc_max_health + self.level * 10
    self.npc_max_speed = npc_max_speed + self.level * 10
    self.npc_name = npc_name
    self.npc_file = npc_file
    self.npc_wild = npc_wild
    self.npc_defense = npc_defense
    self.npc_offense = npc_offense
    self.npc_cur_armor = self.npc_max_armor
    self.npc_cur_speed = self.npc_max_speed
    self.npc_cur_health = self.npc_max_health
    self.npc_cur_attack = self.npc_max_attack
    save!
  end

# stores session ID , used to get players correct game table entry
  def setid(id)
    self.userID = id
    save!
  end


#take player turn, calls all AI helper functions
#To determine moves and winner
  def taketurn(move_type)
    #Npc first
    if self.p_cur_speed < self.npc_cur_speed
      self.npc_first = TRUE
      ai_move
      #Check player health
      if self.p_cur_health <= 0
        self.npc_win = TRUE
        self.retry = TRUE
        self.p_loss_counter +=1
      else
        player_move(move_type)
        #Make sure the NPC hasn't already won since we can't stop
        #in between turns, Check NPC Health
        if self.npc_cur_health <= 0 && self.npc_win != TRUE
          self.p_win = TRUE
        end
      end
    #Player first
    else
      self.p_first = TRUE
      player_move(move_type)
      if self.npc_cur_health <= 0
        self.p_win = TRUE
      else
        ai_move
        if self.p_cur_health <= 0 && self.p_win != TRUE
          self.npc_win = TRUE
          self.retry = TRUE
          self.p_loss_counter +=1
        end
      end
    end
    save!  #update database
  end

  def player_move(move_type)
    #Check possible conditions before move
    if self.p_renew == TRUE
      self.p_cur_health += 6
      if self.p_cur_health > self.p_max_health
        self.p_cur_health = self.p_max_health
      end
      self.p_renew == FALSE
    end
    if self.p_bleed == TRUE
      self.p_cur_health = self.p_cur_health - (self.npc_cur_attack * 0.075) + 2
      self.p_bleed == FALSE
    end

    #Player lost a move, no attack
    if self.p_lose_turn == TRUE
      self.p_lose_turn = FALSE
      self.p_last_move = "No abilities"
    #Player is asleep
    elsif self.p_sleep == TRUE
      self.p_sleep = FALSE
      self.p_last_move = "zzZZzz"
     #Player is confused - hits self
    elsif self.p_confused == TRUE
      self.p_confused = FALSE
      self.p_last_move = "Confused"
      self.p_cur_health = self.p_cur_health - (self.p_cur_attack * 0.1)
      #Player forgot moves - can only normal attack
    elsif self.p_forget == TRUE
      self.p_forget = FALSE
      self.p_last_move = "Forgetful"
      self.npc_cur_health = self.npc_cur_health - (self.p_cur_attack * 0.1) - (self.npc_cur_armor * 0.1) + 10

    elsif move_type == 'Attack'
      self.npc_cur_health = self.npc_cur_health - (self.p_cur_attack * 0.1) - (self.npc_cur_armor * 0.1) + 10
      self.p_last_move = "Attack"
    elsif move_type == 'Defense'
      p_defense_move
      self.p_last_move = self.p_defense
    elsif move_type == 'Offense'
      p_offense_move
      self.p_last_move = self.p_offense
    else
      p_wild_move
      self.p_last_move = self.p_wild
    end
    save!
  end


  def p_defense_move
      if self.p_defense == "Renew"
        self.p_renew = TRUE
        self.p_cur_health += 10
        #Make sure they don't go over max health
        if self.p_cur_health > self.p_max_health
          self.p_cur_health = self.p_max_health
        end
      elsif self.p_defense == "Heal"
        self.p_cur_health += 15
        if self.p_cur_health > self.p_max_health
          self.p_cur_health = self.p_max_health
        end
      #Sleep - heals for a large amount, lose next turn
      else
        self.p_cur_health = self.p_cur_health + (self.p_max_health * 0.1) + 5
        self.p_sleep = TRUE
        if self.p_cur_health > self.p_max_health
          self.p_cur_health = self.p_max_health
        end
      end
  end

  #Offensive moves deal more damage when the enemy is below 25% health
  def p_offense_move
      #ignores some armor
      if self.p_offense == "Pummel"
        if self.npc_cur_health < self.npc_max_health * 0.25
          self.npc_cur_health = self.npc_cur_health - (self.p_cur_attack * 0.15) - (self.npc_cur_armor * 0.05)
        else
          self.npc_cur_health = self.npc_cur_health - (self.p_cur_attack * 0.05) - (self.npc_cur_armor * 0.05)
        end
       #takes recoil damage
      elsif self.p_offense == "Dive"
        if self.npc_cur_health < self.npc_max_health * 0.25
          self.npc_cur_health = self.npc_cur_health - (self.p_cur_attack * 0.175) - (self.npc_cur_armor * 0.1) + 10
          self.p_cur_health = self.p_cur_health - (self.p_cur_attack * 0.1) - (self.p_cur_armor * 0.075) + 5
        else
          self.npc_cur_health = self.npc_cur_health - (self.p_cur_attack * 0.1) - (self.npc_cur_armor * 0.1) + 5
          self.p_cur_health = self.p_cur_health - (self.p_cur_attack * 0.1) - (self.p_cur_armor * 0.075) + 5
        end
      #Poke - bleeds enemy
      else
        if self.npc_cur_health < self.npc_max_health * 0.25
          self.npc_cur_health = self.npc_cur_health - (self.p_cur_attack * 0.175) - (self.npc_cur_armor * 0.1)
          self.npc_bleed == TRUE
        else
          self.npc_cur_health = self.npc_cur_health - (self.p_cur_attack * 0.1) - (self.npc_cur_armor * 0.1) + 4
          self.npc_bleed == TRUE
        end
      end
  end

  #Wild Moves are more effective when the enemy is above 75% health
  def p_wild_move
    #Random chance to lose turn
    if self.p_wild == "Innocence"
      if self.npc_cur_health > self.npc_max_health * 0.75
        i = rand(1..5)
        if i == 1
          self.npc_lose_turn = TRUE
        end
      else
        i = rand(1..10)
        if i == 1
          self.npc_lose_turn = TRUE
        end
      end
      self.npc_cur_health = self.npc_cur_health - 5
    #Enemy may hit itself
    elsif self.p_wild == "Dazzle"
      if self.npc_cur_health > self.npc_max_health * 0.75
        i = rand(1..5)
        if i == 1
          self.npc_confused = TRUE
        end
      else
        i = rand(1..10)
        if i == 1
          self.npc_confused = TRUE
        end
      end
      self.npc_cur_health = self.npc_cur_health - 5
    #Whoosh - chance for enemy to forget attacks
    else
      if self.npc_cur_health > self.npc_max_health * 0.75
        i = rand(1..4)
        if i == 1
          self.npc_forget = TRUE
        end
      else
        i = rand(1..9)
        if i == 1
          self.npc_forget = TRUE
        end
      end
      self.npc_cur_health = self.npc_cur_health - 6
    end

  end

  def npc_defense_move
    #Heal over 2 turns
    if self.npc_defense == "Renew"
      self.npc_renew = TRUE
      self.npc_cur_health += 10
      if self.npc_cur_health > self.npc_max_health
        self.npc_cur_health = self.npc_max_health
      end
    #medium heal
    elsif self.npc_defense == "Heal"
      self.npc_cur_health += 15
      if self.npc_cur_health > self.npc_max_health
        self.npc_cur_health = self.npc_max_health
      end
      #Sleep
    else
      self.npc_cur_health = self.npc_cur_health + (self.npc_max_health * 0.1) + 5
      self.npc_sleep = TRUE
      if self.npc_cur_health > self.npc_max_health
        self.npc_cur_health = self.npc_max_health
      end
    end
    save!
  end

  def npc_offense_move
    if self.npc_offense == "Pummel"
      if self.p_cur_health < self.p_max_health * 0.25
        self.p_cur_health = self.p_cur_health - (self.npc_cur_attack * 0.15) - (self.p_cur_armor * 0.05)
      else
        self.p_cur_health = self.p_cur_health - (self.npc_cur_attack * 0.05) - (self.p_cur_armor * 0.05)
      end
    elsif self.npc_offense == "Dive"
      if self.p_cur_health < self.p_max_health * 0.25
        self.p_cur_health = self.p_cur_health - (self.npc_cur_attack * 0.175) - (self.p_cur_armor * 0.1) + 10
        self.npc_cur_health = self.npc_cur_health - (self.npc_cur_attack * 0.1) - (self.npc_cur_armor * 0.075) + 5
      else
        self.p_cur_health = self.p_cur_health - (self.npc_cur_attack * 0.1) - (self.p_cur_armor * 0.1) + 5
        self.npc_cur_health = self.npc_cur_health - (self.npc_cur_attack * 0.1) - (self.npc_cur_armor * 0.075) + 5
      end
    #Poke
    else
      if self.p_cur_health < self.p_max_health * 0.25
        self.p_cur_health = self.p_cur_health - (self.npc_cur_attack * 0.175) - (self.p_cur_armor * 0.1)
        self.p_bleed == TRUE
      else

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def new
  end
  def games_directions
    render :action => 'directions'
  end
  def show

    @highscores = Highscore.order(p_score: :desc).limit(10)

    render :action => 'highscore'
  end
def update

  @games = Game.all
  id = session[:session_id]
  @game = Game.find_by(userID: id)

  #Win/Lose Update Battlefield
  if params[:option] == 'Decision'
    level = @game.level + 1
    if level <= 7
      @npc = Npc.find_by(level: level)
      @game.update_npc(@npc.npc_name, @npc.npc_file, @npc.npc_wild, @npc.npc_offense,
                    @npc.npc_defense, @npc.npc_max_health, @npc.npc_max_armor,
                    @npc.npc_max_attack, @npc.npc_max_speed)
      @game.continue
    else
      #get highscore table info
      @game.continue
      @highscore = Highscore.new(p_name: @game.p_name, level: @game.level, p_score: @game.p_score)
      @highscore.save

    end
    #Player lost level, reload level
  elsif params[:option] == 'Retry'
    level = @game.level
    @npc = Npc.find_by(level: level)
    @game.update_npc(@npc.npc_name, @npc.npc_file, @npc.npc_wild, @npc.npc_offense,
                     @npc.npc_defense, @npc.npc_max_health, @npc.npc_max_armor,
                     @npc.npc_max_attack, @npc.npc_max_speed)
    @game.continue
  #What attack was pressed
  elsif params[:option] == 'Attack'
    @game.taketurn('Attack')
  elsif params[:option] == 'Defense'
    @game.taketurn('Defense')
  elsif params[:option] == 'Offense'
    @game.taketurn('Offense')
  else
    @game.taketurn('Wild')

  end
  render :action => 'update'

end



def create
  @game = Game.new(game_params)
  @game.setid(session[:session_id])
  @game.init
  #Level 1 enemy
  @npc = Npc.find_by(level: 1)
  @game.update_npc(@npc.npc_name, @npc.npc_file, @npc.npc_wild, @npc.npc_offense,
                  @npc.npc_defense, @npc.npc_max_health, @npc.npc_max_armor,
                  @npc.npc_max_attack, @npc.npc_max_speed)
  @saved = @game.save

  render 'update'
end

private
  def game_params
    params.require(:game).permit(:p_name, :p_color, :p_wild, :p_defense, :p_offense, :p_stat_boost)
  end

end

app/views/games/directions.html.erb
<!DOCTYPE html>
<!-- directions.html.erb -->
<html>
<!--Samantha Holloway Senior Project Oct 2014-->
<head lang="en">
  <%= stylesheet_link_tag "Main.css" %>
  <meta charset="UTF-8">
  <title>Directions</title>
</head>
<body>
<%= image_tag("Headline.jpg", :class => 'WebsiteName', :alt => 'Logo') %>


<h2>Overview</h2>
<p>Starting out in this game, you create your Butterfly Battler (the character<br>
  you will be fighting with). There are a variety of ways that you<br>
  can customize your character. You then begin level 1 and use<br>
  your abilities to defeat your enemy. You will win rewards and<br>
  continue on to the next level if you are victorious. Each round will<br>
  be harder than the last level.<br>

  <br>Your game ends when:
</p>
<ul>
  <li>You lose 2 times :(</li>
  <li>You beat every level!</li>
</ul>
<p>
  Once you have finished, your name may be put into the high score board<br>
  if you are in the top 10.<br>
</p>

<h2>Character Creation</h2>
<p>You are allowed to pick your color, shape, stats, name, and 3 special<br>
  abilities to customize your Butterfly Battler.<em>Once you have created<br>
  your character they can't be changed so choose wisely!</em>The stats <br>
  will affect your overall game-play, strength will make your character <br>
  hit harder, defense will make her take less damage, speed will allow<br>
  you to attack first, and health will give her a larger health pool. <br>
  The 3 special abilities are your choice of what attacks you want your<br>
  battler to have. The other customizations are cosmetic only.<br>
</p>

<h2>Gameplay</h2>
<p>Once you actually start your level, you will have a health bar and<br>
  4 abilities to attack with. Your enemy will also have the same, <br>
  but you will only see their health bar and picture. The objective <br>
  is to use the abilities to get the enemy's health down to 0 before <br>
  they get your battler's down to 0. If you do, you win and advance, <br>
  if you don't you have one more chance to succeed. You are only<br>
  allowed to lose twice before your game is over and you have to start<br>
  over from scratch! The High Score board will allow you to show off<br>
  your skills if you place within the top 10, which is determined by <br>
  how many levels you win before the game ends.<br>
</p>

<h2><%= link_to 'Get Started!', new_game_path %></h2>

</body>
</html>

app/views/games/highscore.html.erb
<!DOCTYPE html>
<!--Samantha Holloway Senior Project Oct 2014-->
<!-- highscore.html.erb -->
<html>
<head lang="en">
  <%= stylesheet_link_tag "Main.css" %>
  <meta charset="UTF-8">
  <title>Character Creation</title>
</head>
<body>
<%= image_tag("Headline.jpg", :class => 'WebsiteName', :alt => 'Logo') %>
<!--High Score Table will go here-->

    <table align="center">
      <thead>
        <tr>
            <th>Name</th>
            <th>Level</th>
            <th>Score</th>
        </tr>
      </thead>
      <tbody>
        <% @highscores.each do |score| %>
          <tr><td><%= score.p_name %></td>
          <td><%= score.level %></td>
          <td><%= score.p_score %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

<h2 id="createLink"><%= link_to 'Play Again!', games_index_path %></h2>

app/views/games/index.html.erb
<!DOCTYPE html>
<!--Samantha Holloway Senior Project Oct 2014-->
<!-- index.html.erb -->
<html>
<head lang="en">
  <%= stylesheet_link_tag "Main.css" %>
  <meta charset="UTF-8">
  <title>Home</title>

</head>
<body>
<%= image_tag("Headline.jpg", :class => 'WebsiteName', :alt => 'Logo') %>

<h2>Welcome to Butterfly Battle!</h2>
<p>The purpose of this site is to allow you to play through an arcade style<br>
  game. You get to customize your own Butterfly Battler to defeat evil enemies<br>
  that get progressively harder as you move through each level. At the end, you<br>
  can enter your name on the High Score table to etch your achievement in history!
</p>
<!--go to directions-->
<p>For a more detailed set of directions go <%= link_to "directions", games_directions_path %>, or click below<br>
  to get started!
</p>

<h1><%= link_to 'Create your Butterfly Battler!', new_game_path %></h1>
</body>
</html>

app/views/games/new.html.erb
<!DOCTYPE html>
<html>
<!--Samantha Holloway Senior Project Nov 2014-->
<!-- new.html.erb -->
<head lang="en">
  <%= stylesheet_link_tag "creation.css" %>
  <%= stylesheet_link_tag "Main.css" %>
  <%= javascript_include_tag "creation.js" %>
  <script src="creation.js"></script>
  <meta charset="UTF-8">
  <title>Character Creation</title>
</head>
<body>
<%= image_tag("Headline.jpg", :class => 'WebsiteName', :alt => 'Logo') %>

<h2>Create Your Character!</h2>

<h2>To start off, choose a name for your character.</h2>

<%= form_for :game, url:games_path do |g| %>

<fieldset>
<div id="namefield" >
  <%= g.text_field :p_name %>
</div>
</fieldset>

<h2>Now, choose your color</h2>
<fieldset>
<div id="colorPicker">
  <%= g.radio_button :p_color, :purple , options ={:onclick=> "pictureChange('purplePicButterfly')"}%>
  <%= label_tag(:color_purple, "Purple") %>
  <%= g.radio_button :p_color, :red , options ={:onclick=> "pictureChange('redPicButterfly')"}%>
  <%= label_tag(:color_red, "Red") %>
  <%= g.radio_button :p_color, :black , options ={:onclick=> "pictureChange('blackPicButterfly')"}%>
  <%= label_tag(:color_black, "Black") %>
  <%= image_tag("transparent.png", :class => 'butterfly', :id => 'purplePicButterfly', :alt => 'Butterfly') %>
  <!-- Transparent image used to place behind a Sprite sheet
   that is used to switch in and out Butterfly Images-->
</div>
</fieldset>


<h2>You get to pick 3 special abilities, 1 from each category.</h2>
  <h2>Defensive Ability</h2>
  <fieldset>
  <div id="defensePicker">
     <%= g.radio_button :p_defense, :Heal , options ={:onclick=> "changeToolTip('HealText', '.DefenseToolTip')"}%>
     <%= label_tag(:defense_heal, "Heal") %>
     <%= g.radio_button :p_defense, :Renew , options ={:onclick=> "changeToolTip('RenewText', '.DefenseToolTip')"}%>
     <%= label_tag(:defense_block, "Renew") %>
     <%= g.radio_button :p_defense, :Sleep , options ={:onclick=> "changeToolTip('SleepText', '.DefenseToolTip')"}%>
     <%= label_tag(:defense_sleep, "Sleep") %>
     <span class="DefenseToolTip" id="HealText">Heal will allow you to heal your character for a medium amount.</span>
     <span class="DefenseToolTip" id="RenewText">Renew will heal you for a large amount over two turns</span>
     <span class="DefenseToolTip" id="SleepText">Sleep will allow you to heal for a large amount, but you
      lose your next turn.</span>
  </div>
  </fieldset>


  <h2>Offensive Ability</h2>
  <fieldset>
  <div id="offensivePicker">
    <%= g.radio_button :p_offense, :Dive , options ={:onclick=> "changeToolTip('DiveText', '.OffenseToolTip')"}%>
    <%= label_tag(:offense_dive, "Dive") %>
    <%= g.radio_button :p_offense, :Pummel , options ={:onclick=> "changeToolTip('PummelText', '.OffenseToolTip')"}%>
    <%= label_tag(:offense_dive, "Pummel") %>
    <%= g.radio_button :p_offense, :Poke , options ={:onclick=> "changeToolTip('PokeText', '.OffenseToolTip')"}%>
    <%= label_tag(:offense_dive, "Poke") %>
    <span class="OffenseToolTip" id="DiveText">Dive lets you fly into the air and then smash into your opponent
    for a large amount of damage, but you take a small amount of damage as well.</span>
    <span class="OffenseToolTip" id="PummelText">You pummel the enemy with your wings, dealing a medium amount
    of damage.</span>
    <span class="OffenseToolTip" id="PokeText">You poke your enemy in the eye with your antennae
    dealing a large amount of damage, your opponent bleeds next turn. Ew.</span>
  </div>
  </fieldset>


  <h2>Wild Ability</h2>
  <fieldset>
  <div id="wildPicker">
    <%= g.radio_button :p_wild, :Dazzle , options ={:onclick=> "changeToolTip('DazzleText', '.WildToolTip')"}%>
    <%= label_tag(:offense_dazzle, "Dazzle") %>
    <%= g.radio_button :p_wild, :Whoosh , options ={:onclick=> "changeToolTip('WhooshText', '.WildToolTip')"}%>
    <%= label_tag(:offense_whoosh, "Whoosh") %>
    <%= g.radio_button :p_wild, :Innocence , options ={:onclick=> "changeToolTip('InnocenceText', '.WildToolTip')"}%>
    <%= label_tag(:offense_Innocence, "Innocence") %>
    <span class="WildToolTip" id="DazzleText">You dazzle the enemy with your beautiful wings, they may only
    normal attack next turn</span>
    <span class="WildToolTip" id="WhooshText">You fly wildly around your enemy, they may hit themselves
    the next turn.</span>
    <span class="WildToolTip" id="InnocenceText">You sit innocently in front of your enemy, they
    may feel too bad to hit you next turn.</span>
  </div>
  </fieldset>


  <h2>Now for your character's stats. You get extra points in one of these.</h2>
  <fieldset>
  <div id="statPicker">
    <%= g.radio_button :p_stat_boost, :Strength , options ={:onclick=> "statChange('Strength')"}%>
    <%= label_tag(:stat_strength, "Strength") %>
    <%= g.radio_button :p_stat_boost, :Defense , options ={:onclick=> "statChange('Defense')"}%>
    <%= label_tag(:stat_defense, "Defense") %>
    <%= g.radio_button :p_stat_boost, :Speed , options ={:onclick=> "statChange('Speed')"}%>
    <%= label_tag(:stat_speed, "Speed") %>
    <%= g.radio_button :p_stat_boost, :Stamina , options ={:onclick=> "statChange('Stamina')"}%>
    <%= label_tag(:stat_stamina, "Stamina") %>
    <span class ="statPicker">
      <%= image_tag("transparent.png", :class => 'stat', :id => 'Strength', :alt => 'Strength') %>

    </span>
  </div>
  </fieldset>



<h2>Check over your selections, they are permanent once you continue.</h2>
<button id="submit"><%= g.submit %></button>



<a href="#name" id="Backtotop">Back to Top</a>
<% end %>
</body>
</html>

app/views/games/update.html.erb
<!DOCTYPE html>
<!--Samantha Holloway Senior Project Nov 2014-->
<!-- update.html.erb -->
<html>
<head lang="en">
  <%= stylesheet_link_tag "Main.css" %>
  <%= stylesheet_link_tag "play.css" %>
  <%= javascript_include_tag "jquery-2.1.1.min" %>
  <%= javascript_include_tag "play" %>
  <meta charset="UTF-8">
  <title>Play!</title>
</head>
<body>


<%= image_tag("Headline.jpg", :class => 'WebsiteName', :alt => 'Logo') %>

<!--Hidden variables for health bars-->
<p class = "hide" id = "npc_max_health"><%= @game.npc_max_health %></p>
<p class = "hide" id = "p_max_health"><%= @game.p_max_health %></p>
<p class = "hide" id = "p_cur_health"><%= @game.p_cur_health %></p>
<p class = "hide" id = "npc_cur_health"><%= @game.npc_cur_health %></p>
<div id = "stageArea">
<div id="versusBox">
  <b>Level <%= @game.level %></b><br> <%= @game.p_name %> <br>Vs<br><%= @game.npc_name %>
</div>
<div id="historyBox">
  <div id="history">
    <p><%= @game.npc_name %></p>
    <% if @game.npc_last_move != 'None' %>
    <p>used <%= @game.npc_last_move %>!</p>
    <% end %>
    <p>NPC Health <%= @game.npc_cur_health %></p>
    <p><%= @game.p_name %></p>
    <% if @game.p_last_move != 'None' %>
        <p>used <%= @game.p_last_move %>!</p>
    <% end %>
    <p> <%= @game.p_name %>'s Health <%= @game.p_cur_health %></p>
  </div>
</div>
<div id="container">
<div id="battlefield">
  <div id="characterfield" >
    <canvas id="phealthbar"></canvas>
        <%= if @game.p_color == "black"
                image_tag("blackButterfly.jpg", :id => 'blackButterfly', :alt => 'blackButterfly')
            elsif @game.p_color == "red"
                image_tag("redButterfly.jpg", :id => 'redButterfly', :alt => 'redButterfly')
            else
                image_tag("purpleButterfly.jpg", :id => 'purpleButterfly', :alt => 'purpleButterfly')
            end
        %>
  </div>
  <div id="npcfield">
    <canvas id="npchealthbar"></canvas>
        <%= image_tag(@game.npc_file, :class =>'npcimage', :id => @game.npc_name, :alt => @game.npc_name) %>
  </div>
</div>
<div id="attacks">
       <%  if @game.over == TRUE %>
       <%= link_to 'High Score', games_highscore_path %>
       <% elsif @game.retry == TRUE %>
       <%= link_to 'Continue', games_update_path(:option => 'Retry') %>
       <%  elsif @game.p_win == FALSE && @game.npc_win == FALSE %>
       <%= link_to 'Attack', games_update_path(:option => 'Attack') %>
       <%= link_to @game.p_defense, games_update_path(:option => 'Defense') %>
       <%= link_to @game.p_offense, games_update_path(:option => 'Offense') %>
       <%= link_to @game.p_wild, games_update_path(:option => 'Wild') %>
       <% else %>
       <%= link_to 'Continue', games_update_path(:option => 'Decision') %>
       <% end %>

</div>
</div>
</div>

</body>
</html>